# Generated by Django 5.0.1 on 2024-03-14 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('is_manager', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='valeur', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project.statu')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtaskof', models.IntegerField()),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=3, max_length=100)),
                ('projet', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.projet')),
                ('status', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='project.statu')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='project.user')),
            ],
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ManyToManyField(default='', to='project.user')),
            ],
        ),
    ]
