# Generated by Django 5.0.1 on 2024-03-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_project', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.IntegerField()),
                ('subtaskof', models.IntegerField()),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('completion_rate', models.DecimalField(decimal_places=2, max_digits=3, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
