# Generated by Django 5.0.1 on 2024-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
