# Generated by Django 5.0.1 on 2024-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_status_remove_projet_id_project_remove_task_id_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='status',
            new_name='statu',
        ),
    ]
