# Generated by Django 5.0.1 on 2024-03-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='name',
            field=models.CharField(default='valeur', max_length=50),
        ),
    ]
